environment:
  randomPOIs: false # New POIs every episode or not?
  numberOfPOIs: 8
  numberOfClassIds: 2
  coupling: 1
  reward: 30
  observationRadius: 5.0
  penalty: -1
  dimensions:
    xLength: 100
    yLength: 100

episode:
  length: 10

team:
  numberOfAgents: 3

agent:
  randomStartPosition: true
  startingX: 9
  startingY: 11
  maxStepSize: 4
  observationRadius: 5
  numberOfSensors: 4

evolutionary:
  populationSize: 3 # Will decide the number of policies for each agent in the population
  numberOfEpisodes: 4
  numberOfGenerations: 50